// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@1.0.0";

// src/lib/mcp/tools/list-releases.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z } from "npm:zod@^3.25.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.58.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-releases.ts
var list_releases_default = defineTool({
  name: "list_releases",
  title: "Lista wyda\u0144 muzycznych",
  description: "Zwraca wydania muzyczne zalogowanego artysty (tytu\u0142, artysta, status, data premiery).",
  inputSchema: {
    status: z.string().optional().describe("Opcjonalny filtr statusu, np. draft, submitted, live"),
    limit: z.number().int().min(1).max(100).default(25).describe("Maksymalna liczba wynik\xF3w")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("music_releases").select("id, title, artist_name, album_type, status, release_date, upc_code, submitted_at, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }], structuredContent: { releases: data } };
  }
});

// src/lib/mcp/tools/list-payouts.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z2 } from "npm:zod@^3.25.0";
var list_payouts_default = defineTool2({
  name: "list_payouts",
  title: "Lista wyp\u0142at",
  description: "Zwraca histori\u0119 wyp\u0142at prowizji zalogowanego tw\xF3rcy wraz ze statusami i okresami rozliczeniowymi.",
  inputSchema: {
    status: z2.enum(["pending", "approved", "processing", "paid", "rejected"]).optional().describe("Opcjonalny filtr statusu"),
    limit: z2.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("payouts").select("id, amount, currency, status, period_start, period_end, reference, requested_at, paid_at").eq("user_id", ctx.getUserId()).order("requested_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }], structuredContent: { payouts: data } };
  }
});

// src/lib/mcp/tools/get-settlement-summary.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@1.0.0";
var get_settlement_summary_default = defineTool3({
  name: "get_settlement_summary",
  title: "Podsumowanie rozlicze\u0144",
  description: "Zwraca podsumowanie finansowe zalogowanego tw\xF3rcy: przych\xF3d brutto, prowizja HRL, zarobek netto, wyp\u0142acono, w realizacji i saldo nierozliczone.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const uid = ctx.getUserId();
    const [{ data: txs, error: e1 }, { data: payouts, error: e2 }] = await Promise.all([
      supabase.from("revenue_transactions").select("gross_amount, amount, platform_fee_amount, net_to_artist, settled_payout_id").eq("user_id", uid),
      supabase.from("payouts").select("amount, status").eq("user_id", uid)
    ]);
    if (e1 || e2) return { content: [{ type: "text", text: (e1 || e2).message }], isError: true };
    const n = (v) => Number(v ?? 0);
    const gross = (txs || []).reduce((a, t) => a + n(t.gross_amount ?? t.amount), 0);
    const fee = (txs || []).reduce((a, t) => a + n(t.platform_fee_amount), 0);
    const net = (txs || []).reduce((a, t) => a + n(t.net_to_artist ?? t.amount), 0);
    const unsettled = (txs || []).filter((t) => !t.settled_payout_id).reduce((a, t) => a + n(t.net_to_artist ?? t.amount), 0);
    const paid = (payouts || []).filter((p) => p.status === "paid").reduce((a, p) => a + n(p.amount), 0);
    const inProgress = (payouts || []).filter((p) => ["pending", "approved", "processing"].includes(p.status)).reduce((a, p) => a + n(p.amount), 0);
    const summary = {
      currency: "PLN",
      gross: +gross.toFixed(2),
      platform_fee: +fee.toFixed(2),
      net_earned: +net.toFixed(2),
      paid_out: +paid.toFixed(2),
      in_progress: +inProgress.toFixed(2),
      unsettled_balance: +unsettled.toFixed(2),
      transactions: txs?.length ?? 0,
      payouts: payouts?.length ?? 0
    };
    return { content: [{ type: "text", text: JSON.stringify(summary, null, 2) }], structuredContent: summary };
  }
});

// src/lib/mcp/tools/list-disputes.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z3 } from "npm:zod@^3.25.0";
var list_disputes_default = defineTool4({
  name: "list_payout_disputes",
  title: "Lista spor\xF3w wyp\u0142at",
  description: "Zwraca spory zg\u0142oszone przez zalogowanego tw\xF3rc\u0119 do pozycji wyp\u0142at wraz ze statusem i rozstrzygni\u0119ciem.",
  inputSchema: {
    status: z3.enum(["open", "under_review", "resolved", "rejected"]).optional(),
    limit: z3.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("payout_disputes").select("id, payout_item_id, reason, disputed_amount, status, resolution, created_at, resolved_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }], structuredContent: { disputes: data } };
  }
});

// src/lib/mcp/tools/create-dispute.ts
import { defineTool as defineTool5, ToolError } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z4 } from "npm:zod@^3.25.0";
var create_dispute_default = defineTool5({
  name: "create_payout_dispute",
  title: "Zg\u0142o\u015B sp\xF3r do pozycji wyp\u0142aty",
  description: "Tworzy sp\xF3r do wskazanej pozycji wyp\u0142aty (payout_item) zalogowanego tw\xF3rcy. Administrator otrzyma go do rozpatrzenia.",
  inputSchema: {
    payout_item_id: z4.string().uuid().describe("ID pozycji wyp\u0142aty"),
    reason: z4.string().trim().min(10).max(2e3).describe("Opis problemu (min. 10 znak\xF3w)"),
    disputed_amount: z4.number().nonnegative().optional().describe("Kwestionowana kwota (opcjonalnie)")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ payout_item_id, reason, disputed_amount }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("payout_disputes").insert({ payout_item_id, reason, disputed_amount: disputed_amount ?? null, user_id: ctx.getUserId() }).select("id, status, created_at").single();
    if (error) throw new ToolError(error.message);
    return { content: [{ type: "text", text: `Sp\xF3r utworzony: ${data.id}` }], structuredContent: { dispute: data } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ipmwxzxthrdqxqgjonru";
var mcp_default = defineMcp({
  name: "hardbanrecordslab-userhub",
  title: "hardbanrecordslab-userhub",
  version: "0.1.0",
  instructions: "Narz\u0119dzia HardbanRecords Lab dla zalogowanego artysty/autora: przegl\u0105d wyda\u0144 muzycznych, wyp\u0142at prowizji, podsumowania rozlicze\u0144 oraz zg\u0142aszanie spor\xF3w do pozycji wyp\u0142at. Wszystkie dane s\u0105 ograniczone do konta u\u017Cytkownika, kt\xF3ry autoryzowa\u0142 po\u0142\u0105czenie.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_releases_default, list_payouts_default, get_settlement_summary_default, list_disputes_default, create_dispute_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@1.0.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
