// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ipmwxzxthrdqxqgjonru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwbXd4enh0aHJkcXhxZ2pvbnJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzNTk5NTMsImV4cCI6MjA3NDkzNTk1M30.xr-fA7qct8mrB6jm4-HmoOvjvV4Y2h89_VBoPiSLIro";

// Standard Supabase client (Lovable Cloud). Auth session is persisted in
// localStorage and auto-refreshed. All previous "HRLBridge" usage has been
// removed because it broke storage, RLS (auth.uid()), and query chaining.
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
